name: loop
on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'Name of the solution to worked on from Power Platform'
        required: true
        default: FSK_Webresources, FSK_Entities, FSK_Plugins, FSK_Processes
jobs:
  install:
    strategy:
      matrix:
        solutions: [FSK_Webresources, FSK_Entities, FSK_Plugins, FSK_Processes]
    runs-on: [ubuntu-latest]
    steps:
      - name: deploy
        run: |
          echo Deploying solution ${{ matrix.solutions }} !
      - run: date
      - run: sleep 3

