# This is a basic workflow to help you get started with Actions
name: deploy-solution

# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: KIWI_Transport
  release:
    types: [created]

env:
#edit your values here
  ENVIRONMENT_URL: https://rtekiwidev.crm4.dynamics.com/
  PRODUCTION_ENVIRONMENT_URL: https://kiwi-rte-uat.crm4.dynamics.com/
  USERNAME: gilles.bandza_ibm@rtefrance.onmicrosoft.com
  solution_release_folder: out/release
  solution_exported_folder: out/exported/

jobs:
  export-from-dev:
    name: Build solution
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@0.4.0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        user-name: ${{env.USERNAME}}
        password-secret: ${{ secrets.password }}

    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@0.4.0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        user-name: ${{env.USERNAME}}
        password-secret: ${{ secrets.password }}
        solution-name: ${{ github.event.inputs.solution_name }}
        managed: true
        solution-output-file: ${{ env.solution_exported_folder }}/${{ github.event.inputs.solution_name }}.zip

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: ${{ env.solution_exported_folder }}/${{ github.event.inputs.solution_name }}.zip

  release-to-staging:
    needs: [ export-from-dev ]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: out/release/

    - name: Import solution to staging env
      uses: microsoft/powerplatform-actions/import-solution@0.4.0
      with:
        environment-url: ${{env.PRODUCTION_ENVIRONMENT_URL}}
        user-name: ${{env.USERNAME}}
        password-secret: ${{ secrets.password }}
        solution-file: ${{env.solution_release_folder}}/${{ github.event.inputs.solution_name }}.zip
        force-overwrite: true
        publish-changes: true

